export const generationMeta = [
  { id: 3, label: "Наши дни", short: "Сегодня", tone: "green" },
  { id: 2, label: "Поколение · 1970-е", short: "1970-е", tone: "green" },
  { id: 1, label: "Ветвь · 1910-е", short: "1910-е", tone: "gold" },
  { id: 0, label: "Корни · 1880-е", short: "1880-е", tone: "terracotta" },
];

export const seedPeople = [
  {
    id: "petr",
    name: "Пётр Петров",
    birth: "1858",
    death: "1926",
    relation: "прадед",
    generation: 0,
    parents: [],
    partnerId: "maria",
    birthplace: "Тверская губерния",
    occupation: "Плотник",
    note: "Демонстрационная запись. Замените её сведениями своей семьи.",
  },
  {
    id: "maria",
    name: "Мария Петрова",
    birth: "1861",
    death: "1933",
    relation: "прабабушка",
    generation: 0,
    parents: [],
    partnerId: "petr",
    birthplace: "Тверская губерния",
    occupation: "Хозяйка дома",
    note: "Хранила письма и семейные фотографии.",
  },
  {
    id: "ivan",
    name: "Иван Петров",
    birth: "1888",
    death: "1962",
    relation: "дед",
    generation: 1,
    parents: ["petr", "maria"],
    partnerId: "anna",
    birthplace: "Кашин",
    occupation: "Инженер",
    note: "Любил мастерить и оставил семейный альбом.",
  },
  {
    id: "anna",
    name: "Анна Петрова",
    birth: "1892",
    death: "1971",
    relation: "бабушка",
    generation: 1,
    parents: [],
    partnerId: "ivan",
    birthplace: "Кашин",
    occupation: "Учительница",
    note: "Вела семейные записи и собирала старые фотографии.",
  },
  {
    id: "mikhail",
    name: "Михаил Петров",
    birth: "1946",
    death: "2018",
    relation: "отец",
    generation: 2,
    parents: ["ivan", "anna"],
    partnerId: "natalia",
    birthplace: "Москва",
    occupation: "Архитектор",
    note: "Продолжил семейную традицию бережно хранить документы.",
  },
  {
    id: "natalia",
    name: "Наталья Петрова",
    birth: "1946",
    death: "",
    relation: "мать",
    generation: 2,
    parents: [],
    partnerId: "mikhail",
    birthplace: "Москва",
    occupation: "Врач",
    note: "Подписала большую часть фотографий в семейном архиве.",
  },
  {
    id: "alexey",
    name: "Алексей Петров",
    birth: "1952",
    death: "",
    relation: "дядя",
    generation: 2,
    parents: ["ivan", "anna"],
    partnerId: "",
    birthplace: "Москва",
    occupation: "Геолог",
    note: "Привозил из экспедиций письма и фотографии.",
  },
  {
    id: "pavel",
    name: "Павел Соколов",
    birth: "1890",
    death: "1958",
    relation: "брат бабушки",
    generation: 1,
    parents: [],
    partnerId: "lidia",
    birthplace: "Кашин",
    occupation: "Агроном",
    note: "Демонстрационная боковая ветвь семьи.",
  },
  {
    id: "lidia",
    name: "Лидия Соколова",
    birth: "1895",
    death: "1965",
    relation: "сестра бабушки",
    generation: 1,
    parents: [],
    partnerId: "pavel",
    birthplace: "Кашин",
    occupation: "Швея",
    note: "Сохранила несколько семейных писем.",
  },
  {
    id: "sergey",
    name: "Сергей Петров",
    birth: "1970",
    death: "",
    relation: "сын",
    generation: 3,
    parents: ["mikhail", "natalia"],
    partnerId: "elena",
    birthplace: "Москва",
    occupation: "Фотограф",
    note: "Оцифровывает семейный архив.",
  },
  {
    id: "elena",
    name: "Елена Петрова",
    birth: "1973",
    death: "",
    relation: "супруга",
    generation: 3,
    parents: [],
    partnerId: "sergey",
    birthplace: "Ярославль",
    occupation: "Редактор",
    note: "Собирает устные истории родственников.",
  },
];
